services:
  - type: web
    name: Twitter_Sentiment_Analysis_Project
    env: python
    region: frankfurt

    buildCommand: |
      pip install -r requirements.txt
      python -m nltk.downloader -d nltk_data stopwords
      python -m nltk.downloader -d nltk_data wordnet
      python -m nltk.downloader -d nltk_data punkt
      python -m nltk.downloader -d nltk_data punkt_tab

    startCommand: "gunicorn app:app"
